---
- hosts: 172.31.25.220
  become: yes
  tasks:
   - name: i want to excute linux command
     command: hostname -f
     register: myresult
     
   - name: i want to display 1st myresult
     debug:
       msg: "{{myresult}}"

