---
- hosts: 172.31.25.220
  become: yes
  tasks:
   - name: i want to excute linux command
     command: hostname -f
     register: myresult

   - name: i want to display 1st myresult
     debug:
       msg: "{{myresult}}"

   - name: i want to install git
     apt: 
      name: git
      state: present
     when: myresult ==""

   - name: i want to install tree
     apt: 
       name: tree
       state: present
     when: myreslt !=""          

