---
- hosts: 172.31.25.220
  become: yes
  vars:
   myvars01: git
   myvars02: tree
   myvars03: wget
  tasks:
   - name: i want to display
     debug:
       msg: git 

   - name: i want to install myvars02
     apt:
       name: "{{myvars02}}"    
       state: present

     loop:
      - git
      - tree
      - wget
