---
- hosts: mywebservers
  become: yes
  tasks:
   - name: i want to install webservice on ansible ubuntu nodes
     apt: 
      name: "{{mywebpackinstallonubuntu}}"
      state: present
     when: ansible_os_family =="Debian"  
     
   - name: i want to start webservice on ansible ubuntu nodes
     service:
        name: "{{mywebpackinstallonubuntu}}"
        state: started
     when: ansible_os_family =="Debian"    

   - name: i want to install webserver on ansible RedHat nodes
     yum:
       name: "{{mywebpackinstallonRedHat}}"
       state: present
     when: ansible_os_family =="RedHat"

   - name: i want to start webserver on ansible RedHat nodes
     service:
        name: "{{mywebpackinstallonRedHat}}"
        state: started
     when: ansible_os_family =="RedHat"            
      