---
- hosts: mywebservers
  become: yes
  tasks:
   - name: i want to install webservice on ansible ubuntu nodes
     apt: 
      name: apache2
      state: present
     when: ansible_os_family =="Debian"  
     
   - name: i want to start webservice on ansible ubuntu nodes
     service:
        name: apache2
        state: started
     when: ansible_os_family =="Debian"    

   - name: i want to install webserver on ansible RedHat nodes
     yum:
       name: httpd
       state: present
     when: ansible_os_family =="RedHat"

   - name: i want to start webserver on ansible RedHat nodes
     service:
        name: httpd
        state: present 
     when: ansible_os_family =="RedHat"            
      